name: Document Deployment

on:
  push:
    branches: [docs]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: docs
      - name: Build Document
        run: yarn install && yarn run build
      - name: Deploy Document
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: twmud.in
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: gh-pages
          force_orphan: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
